version: "2"

linters:
  settings:
    govet:
      disable:
        - composites

    errcheck:
      exclude-functions:
        - (*os.File).Close
        - (io/fs.File).Close
        - io.Copy(*bytes.Buffer)
        - io.Copy(os.Stdout)
        - io.Copy(os.Stderr)
        - (*bytes.Buffer).Write
        - (*bytes.Buffer).WriteByte
        - (*bytes.Buffer).WriteString
        - (*http.Response).Body.Close

    misspell:
      locale: US
